### ISSUE TITLE
Honda specific pids

### ISSUE THREAD

**Issue by overzealus** [kerpz/ArduinoHondaOBD#13]
Hello! I can see from screenshot that you have Honda specific pids.
Can you share them? In a csv file or something.
And can you tell, what Honda models (or ages) do they fit?

**Comment by Daggers9** [comment]
Added some raw data to wiki

**Comment by overzealus** [comment]
Could you be so kind to post csv from torque with equations and header info?

**Comment by Daggers9** [comment]
I'm not quite sure what you are asking for.

but I'm not using torque or any similar apps. I'm simply working on an arduino based stand alone diagnostics device.

**Comment by overzealus** [comment]
I’m talking about torque app screenshots, that you have in Readme.md
