### ISSUE TITLE
Arduino Uno HC-06 Bluetooth Module

### ISSUE THREAD

**Issue by mikewing94** [kerpz/ArduinoHondaOBD#14]
Hello,

I am trying to get this working for my Honda S-MX 1997 (OBD1).

Will this work with the HC-06 Bluetooth module, as my phone doesn't seem to want to connect to it currently?

Thanks

**Comment by eugjr** [comment]
Hello, first of all, make sure your HC-06 board is working properly. You can try some simple Arduino codes to make sure you can pair your BT module and cellphone.
Also make sure the wiring is correct.

**Comment by mikewing94** [comment]
Thank you, I know the HC-06 board is working properly as I have used it in other projects previously. I will re-do the wiring tonight so I can be certain it is correct though.

**Comment by mr-sneezy** [comment]
I use one of the many Android BT serial terminal apps to test my HC-05 modules.

**Comment by kerpz** [comment]
Fixed, added a delay on the bt proc
