### ISSUE TITLE
No Input messages

### ISSUE THREAD

**Issue by mikewing94** [kerpz/ArduinoHondaOBD#15]
Does the program currently give any error messages on the LCD if there is no data being read? I have followed the diagram for the wiring, but I am yet to test it on the car, I am just being shown a blank screen currently, is this normal?

Thanks

**Comment by Daggers9** [comment]
What version of the code are you using?

HOBD_UNI
or 
HOBD_LCD

**Comment by mikewing94** [comment]
HOBD_UNI
    On Monday, March 12, 2018, 7:58:01 AM GMT, Daggers9 <notifications@github.com> wrote:  
 
 
What version of the code are you using?

HOBD_UNI
or
HOBD_LCD
