### ISSUE TITLE
Intent to create Wiki

### ISSUE THREAD

**Issue by Daggers9** [kerpz/ArduinoHondaOBD#16]
Essentially I'd like to create a Wiki for this project for some of the less known/lost pieces of information required to communicate and translate honda ecu data

Information that I'd like to source and confirm

PID/ECU communication | I've already found a few reliable sources from various forums that appear to be correct, next steps for this is to make a master spread sheet

--

ECU Byte/Word conversion | There are various readings made by the ECU which are stored as values between 0 and 255 or 511. After the micro controller receives one or two byte pieces of information, it must convert these values into real world values like temperatures, degrees of advance, percentages...

I'd like to collect and confirm as many conversion formulas and sources as possible.

--

If anybody has any sources (i.e. forums) or and raw data that could be formatted into a document by myself, I'd love to know about it.

**Comment by mikewing94** [comment]
Sounds great! 
Especially for less well known Hondas, (I am currently trying to get this working with a Honda S-MX 1997.)

I think it would also be good if we could get together peoples photographs of wiring etc... I am 99% sure I have a wiring problem with my project currently, but cannot see where from looking at the diagram on here...

**Comment by Daggers9** [comment]
My understanding is that this information will be mostly universal for all Hondas that have ecus before 2002.

My project wiring is completely different from this project as I've created an embedded, stand alone device using completely different display components and a bluetooth delete

**Comment by mikewing94** [comment]
I'd be happy to get anything working currently, I have had bluetooth issues in the past so a stand alone setup would be fine for me also. Would you mind sharing your setup if possible?
