### ISSUE TITLE
ArduinoHondaOBD

### ISSUE THREAD

**Issue by sw2ncx** [kerpz/ArduinoHondaOBD#17]
Is that code working with Ectune????
Or only stock and Crome?

**Comment by kerpz** [comment]
I have no idea what protocol is ectune using.

**Comment by ExGeniusF** [comment]
Hey. Is there a table in the csv format for App TORQUE? In the screenshot there are added PIDs, I do not understand how to add them correctly.

**Comment by rubensx** [comment]
> Hey. Is there a table in the csv format for App TORQUE? In the screenshot there are added PIDs, I do not understand how to add them correctly.

to put csv file in torque you need a file explorer on your android phone like a "X-plore'. app, and root rights to put CSV in the extendedPiDs folder under .torque folder!
