### ISSUE TITLE
Is possible to make RealDash working?

### ISSUE THREAD

**Issue by snowcatjoey** [kerpz/ArduinoHondaOBD#23]
Torque Pro is working great! but i try another apps like RealDash, no response...

**Comment by kerpz** [comment]
Yes I make it work on Realdash :)

**Comment by snowcatjoey** [comment]
I used hobd.fzz's code, Torque Pro still GOOD. But.....RealDash still no response, LCD(16x2) just show "Bluetooth Mode" for 1 second   :(

Do I have to set something in RealDash?  Like "Source: OBD2" "Protocol: ISO 9141-2"
Thank you again for this lovely and useful present!   ^o^

**Comment by kerpz** [comment]
Will check again, I haven't used it for a long time.
