### ISSUE TITLE
Hey! new here

### ISSUE THREAD

**Issue by KrunoslavKrainovic** [kerpz/ArduinoHondaOBD#29]
Is there any documentation how to make everything works? i have arduino uno and lcd screen and i have ectune rom on my ecu, how can i get data from ecu? I want to make for my self digital dashboard but i dont know how to request data from ecu, if anyone would help it would be awesome

**Comment by rubensx** [comment]
your ECU don't have DLC codes out from 3 pin data link plug anymore. Since you modded your ecu, the datalogger has a specific protocol and you can see over bluetooth wiring the module as is: https://www.burton-racing.com/products/bluetooth-datalogger
