### ISSUE TITLE
Question about ECT formula ?

### ISSUE THREAD

**Issue by mr-sneezy** [kerpz/ArduinoHondaOBD#3]
Hi Philip, where did you get the formula for the ECT calculation in degrees C ?
Regards,
Martin

**Comment by kerpz** [comment]
I think from the hondamotors.ru furom they have the formula

**Comment by mr-sneezy** [comment]
I found a look up table apparently read from an OBD1 ECU if I understand it right. here on an old Honda forum.
http://www.getglitched.com/pgmfiwiki/www.pgmfi.org/twiki/bin/view/Library/EngineCoolantTemperature.html
If it's valid then it perhaps could be used as a table in in the HondaOBD code, or used to validate the formula currently used.

I also found this website which can derive the formula for you from points on the curve.
http://rusefi.com/articles/measuring_temperature/Steinhart-Hart.shtml

Here's the sensor curve that Honda quote for sensor testing.
![image](https://cloud.githubusercontent.com/assets/6261419/10266665/2e841d5a-6ab6-11e5-8f5d-faf3d9f2ffcc.png)

In table form.

k-ohm: temp (celsius)(*F)
12 - ( -20) (-4)
5.0 - 0 (32)
2.0 - 20 (68)
1.2 - 40 (104)
0.7 - 60 (140)
0.4 - 80 (176)
0.2 - 100 (212)
0.1 - 120 (248)

Next time I get the car out I'll try to read the raw hex from the DLC and tag with either sensor voltage or a thermocouple on the thermostat housing as it warms up,so I have some verified data points myself.

**Comment by mr-sneezy** [comment]
![lashup](https://cloud.githubusercontent.com/assets/6261419/10266692/83d9c94c-6ab8-11e5-8b7b-00583974df51.JPG)
![dlc_data](https://cloud.githubusercontent.com/assets/6261419/10266693/8784e2b6-6ab8-11e5-923d-0c98b76142c7.JPG)

**Comment by kerpz** [comment]
nice

**Comment by kerpz** [comment]
why is the E16 is less than I17 intake is hotter than the engine :D
