### ISSUE TITLE
connect with chrome ecu software

### ISSUE THREAD

**Issue by dibugreen** [kerpz/ArduinoHondaOBD#4]
hi .. 
i'm blind about arduino :).. wuff ..  see lot of awesome project based n arduino .. including this one :)..
is possible to connect your project with  FT232RL FTDI USB to TTL ..(maybe chrome application will accept this communication..)
sorry for my english..
and thx for advance

**Comment by kerpz** [comment]
Yes, you can use arduino to connect your ecu to crome application, eliminating the use of usb ftdi to ttl connector.

**Comment by dibugreen** [comment]
thx  very much .. i'll try lean arduino .of course based on your project help me very much  ..thx u very much sir ..

**Comment by mr-sneezy** [comment]
Crome PC app connection.
Do you both mean to a PC via the bluetooth link ?
If so what Hardware and Port setting are used in Crome to connect to a stock ECU ?
Regards,
Martin

**Comment by kerpz** [comment]
yes I think its possible with bluetooth too.
